# from core.exceptions import CustomException


# class PasswordDoesNotMatchException(CustomException):
#     code = 401
#     error_code = "USER_PASSWORD_DOES_NOT_MATCH"
#     message = "password does not match"


# class DuplicateEmailException(CustomException):
#     code = 400
#     success = False
#     message = "Duplicated Email"


# class UserNotFoundException(CustomException):
#     code = 404
#     error_code = "USER__NOT_FOUND"
#     message = "user not found"